SMSHubServer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('campaigns/', include(('campaign.urls','campaigns'), namespace='campaigns')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

]

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

campaign/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('add/', views.add, name='add'),
]

accounts/models.py
from django.db import models

# Create your models here.

campaign/models.py
from django.contrib.auth.models import User
from django.db import models

class CampaignStatus(models.Model):
    name = models.CharField(max_length=200)

class Campaign(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    sourcefile = models.FileField(upload_to='sources')
    datetime = models.DateTimeField(auto_now_add=True, blank=True)
    status = models.ForeignKey(CampaignStatus, on_delete=models.CASCADE)

class CampaignStatusChange(models.Model):
    status = models.ForeignKey(CampaignStatus, on_delete=models.CASCADE)
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True, blank=True)

class MessageStatus(models.Model):
    name = models.CharField(max_length=200)

class Message(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    status = models.ForeignKey(MessageStatus, on_delete=models.CASCADE)

class MessageStatusChange(models.Model):
    status = models.ForeignKey(MessageStatus, on_delete=models.CASCADE)
    campaign = models.ForeignKey(Message, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True, blank=True)

class Contact(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    number = models.CharField(max_length=100)

campaign/forms.py
from campaign.models import Campaign
from django.forms import ModelForm

class CampaignForm(ModelForm):
    class Meta:
        model = Campaign
        exclude = ['status', 'user']

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

campaign/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .forms import *
from campaign.models import Campaign, CampaignStatus, CampaignStatusChange
from django.contrib import messages

@login_required
def index(request):
    campaigns = Campaign.objects.all()
    return render(request, 'campaign/index.html', {
        'campaigns': campaigns
    })

@login_required
def add(request):
    errors = False
    if request.method == 'POST':
        form = CampaignForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.status = CampaignStatus.objects.get(name='Pending')
            form.save()
            messages.add_message(request, messages.INFO, 'Campaign saved')
            return index(request)
        else:
            errors = form.errors
    form = CampaignForm()
    return render(request, 'campaign/add.html',{
        'form': form,
        'errors': errors
    })

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Campaign manager{% endblock %}</title>
</head>
<body>
  <main>
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}
    {% if errors %}
    <ul class="messages">
        {% for field, messages in errors.items %}
        <li class="error">{{ field }}: </li>
          {% for message in messages %}
              {{ message }}
          {% endfor %}
        {% endfor %}
    </ul>
    {% endif %}
    {% if user.is_authenticated %}
    <p>
        <a href="{% url 'campaigns:index' %}">Campaigns</a> | 
        <a href="{% url 'campaigns:add' %}">Add Campaign</a> | 
      <a href="{% url 'logout' %}">logout</a>
    </p>
    {% endif %}
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/campaign/add.html
{% extends 'base.html' %}
{% block title %}New campaign{% endblock %}
{% block content %}
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
{% endblock %}

templates/campaign/index.html
{% extends 'base.html' %}
{% block title %}List campaigns{% endblock %}
{% block content %}
{% for campaign in campaigns %}
{{ campaign.datetime|date:'Y-m-d H:i:s' }} {{ campaign.name }}
{% endfor %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if not user.is_authenticated %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
  <p><a href="{% url 'signup' %}">register</a></p>
{% endif %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}